schema:
  - ./src/schema/**/*.ts:
      require: ts-node/register
extensions:
  codegen:
    src/generated-types.ts:
      - typescript
      - typescript-resolvers
  generate:
    db:
      database: pg
      dbConfig:
        database: users
        host: localhost
        password: postgres
        port: 55432
        user: postgresql
    folders:
      schema: ./src/schema
      model: ./model
      resolvers: ./src/resolvers
    graphqlCRUD:
      create: true
      delete: false
      disableGen: false
      find: true
      findAll: true
      subCreate: false
      subDelete: false
      subUpdate: false
      update: true
